name: flame_shooter
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flame: ^1.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/bullets/
    - assets/images/explosion/
    - assets/images/items/
    - assets/images/meteor/
    - assets/images/parallax/
    - assets/images/ships/
    - assets/audio/
  uses-material-design: true
